In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
dir = r'C:\Users\James Stanley\Desktop\Stocks'

In [18]:
import pandas as pd
import os
import glob
  
  
# use glob to get all the csv files 
# in the folder
path = r'C:\Users\James Stanley\Desktop\Stocks'
csv_files = glob.glob(os.path.join(path, "*.csv"))
  
col_names = []
concat_df = []

# loop over the list of csv files
for f in csv_files:
      
    # read the csv file
    df = pd.read_csv(f,parse_dates=True,index_col='time')

    col_names.append(f.split(r"""BATS_""")[-1].split(",")[0]+'_close')
    # print(df)   
    df.rename(columns = {'close': f.split(r"""BATS_""")[-1].split(",")[0] + '_close'},inplace=True)
    # print(df[col_names[-1]])
    concat_df.append(df[col_names[-1]])

In [17]:
print(concat_df)

[]

In [19]:
df2 = pd.concat(concat_df, axis=1)

In [20]:
df2.head()

,DAX_close,ECH_close,EEM_close,EIDO_close,EPU_close,EWA_close,EWJ_close,EWM_close,EWT_close,EWZ_close,FEZ_close,MCHI_close,SPY_close,THD_close
time,,,,,,,,,,,,,,
1993-01-29 14:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.93800,NaN
1993-02-01 14:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.25000,NaN
1993-02-02 14:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.34375,NaN
1993-02-03 14:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.81250,NaN
1993-02-04 14:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.00000,NaN

In [21]:
df2.corr()

,DAX_close,ECH_close,EEM_close,EIDO_close,EPU_close,EWA_close,EWJ_close,EWM_close,EWT_close,EWZ_close,FEZ_close,MCHI_close,SPY_close,THD_close
DAX_close,1.000000,0.157240,0.883982,0.211149,0.441180,0.799323,0.841190,-0.021614,0.618966,0.378182,0.931206,0.744894,0.478476,0.478882
ECH_close,0.157240,1.000000,0.191477,0.786431,0.778093,0.366272,-0.556632,0.758533,-0.520340,0.762922,-0.086632,-0.367917,-0.680395,-0.009800
EEM_close,0.883982,0.191477,1.000000,0.165703,0.435626,0.884637,0.625057,0.368218,0.643927,0.588576,0.454928,0.781939,0.527079,0.564487
EIDO_close,0.211149,0.786431,0.165703,1.000000,0.734084,0.550606,-0.510272,0.675666,-0.426129,0.709913,-0.144392,-0.363611,-0.562644,0.233215
EPU_close,0.441180,0.778093,0.435626,0.734084,1.000000,0.504812,-0.253196,0.463676,-0.228331,0.650384,-0.063802,0.007682,-0.360564,0.302415
EWA_close,0.799323,0.366272,0.884637,0.550606,0.504812,1.000000,0.383381,0.529561,0.525165,0.766459,0.673185,0.148282,0.499018,0.485454
EWJ_close,0.841190,-0.556632,0.625057,-0.510272,-0.253196,0.383381,1.000000,0.012857,0.827329,0.154964,0.615395,0.835562,0.645229,0.599613
EWM_close,-0.021614,0.758533,0.368218,0.675666,0.463676,0.529561,0.012857,1.000000,-0.117313,0.715167,0.136288,-0.499532,-0.201209,-0.000540
EWT_close,0.618966,-0.520340,0.643927,-0.426129,-0.228331,0.525165,0.827329,-0.117313,1.000000,0.086592,0.340702,0.698923,0.934354,0.466302
EWZ_close,0.378182,0.762922,0.588576,0.709913,0.650384,0.766459,0.154964,0.715167,0.086592,1.000000,0.449493,-0.231396,-0.084640,-0.320743
FEZ_close,0.931206,-0.086632,0.454928,-0.144392,-0.063802,0.673185,0.615395,0.136288,0.340702,0.449493,1.000000,0.615306,0.161596,0.170920
MCHI_close,0.744894,-0.367917,0.781939,-0.363611,0.007682,0.148282,0.835562,-0.499532,0.698923,-0.231396,0.615306,1.000000,0.638369,0.415413
SPY_close,0.478476,-0.680395,0.527079,-0.562644,-0.360564,0.499018,0.645229,-0.201209,0.934354,-0.084640,0.161596,0.638369,1.000000,0.540174
THD_close,0.478882,-0.009800,0.564487,0.233215,0.302415,0.485454,0.599613,-0.000540,0.466302,-0.320743,0.170920,0.415413,0.540174,1.000000